### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gprime31** [firatesatoglu/Shodan-searchScript#1]
![2023-03-31_11-43](https://user-images.githubusercontent.com/44535257/229167609-bf44f886-9e98-45a3-9c2e-12e2b5f658c5.png)
python 3.10 ^^
![2023-03-31_11-44](https://user-images.githubusercontent.com/44535257/229167925-daff979a-aa0d-4c45-bb51-7a705d42efb7.png)
python3.8 ^^

**Comment by firatesatoglu** [comment]
Are u sure change api key in source code?

**Comment by gprime31** [comment]
Yes but it helps if I would use one that's not expired ,  xD 
Works great now !

**Comment by gprime31** [comment]
is there a way ot show the full url?

**Comment by gprime31** [comment]
Is there a program to pull urls from shodan?
example:
http.title: Login
instead of having to right click each one to get the url

**Comment by firatesatoglu** [comment]
I edited the script for give the urls. can you try?

**Comment by gprime31** [comment]
it's better
but can you make it show the urls?
example:   http.title:"grafana"
![2023-03-31_12-40](https://user-images.githubusercontent.com/44535257/229179866-17182f7a-598b-4573-b70b-55e41bcd46b4.png)

then instead of having to click each red arrow it will show the urls?
so I don't have to click one by one.

**Comment by firatesatoglu** [comment]
I think I understand what you want. You want the address of the application, right?

**Comment by gprime31** [comment]
ya so this:
![2023-03-31_12-57](https://user-images.githubusercontent.com/44535257/229183423-4676ec8d-f304-4086-8f73-5712a742fb09.png)

shows as:
http://52.28.13.226:3000/login
http://43.143.196.13:3000/login
https://34.86.123.21/login

in a txt file
or in the cli
